server:
  port: 8083

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST    
              - OPTIONS
              - PUT
      routes:
      
      - id: keycloak-api-service
        uri: http://localhost:9081/
        predicates:
          - Path=/auth/**

      - id: vendas-api-service
        uri: http://localhost:8081/
        
        predicates:
          - Path=/vendas/**
        filters:
          - RewritePath=/vendas, /
          
      - id: administrador-api-service
        uri: http://localhost:8083/
        predicates:
          - Path=/administrador/**   
        filters:
          - RewritePath=/administrador, / 



        