version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "stellatoTech"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./Docker-Compose/PostgreSQL:/var/lib/postgresql/data