version: '3.1'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_DB: "stellatoVendas"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/rober/Documents/stellato/stellato-back-end/api-vendas/docker/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "roberto.sxav@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge