version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    tty: true
    volumes:
      - ./Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    ports:
      - 5432:5432          
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5 
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stellatoTech
      - POSTGRES_SSL=false