CREATE TABLE TB_LEAD (
 	ID_LEAD SERIAL CONSTRAINT PK_ID_LEAD PRIMARY KEY,
 	NOME VARCHAR(100) NOT NULL,
 	EMAIL VARCHAR(200),
 	TELEFONE VARCHAR(11) NOT NULL,
 	CONSUMO NUMERIC(10,2) NOT NULL,
 	CIDADE VARCHAR(250) NOT NULL,
 	TIPO_TELHA NUMERIC(2) NOT NULL,
 	ORIGEM NUMERIC(2) NOT NULL,
 	STATUS NUMERIC(1) DEFAULT 1
);
COMMENT ON TABLE TB_LEAD IS 'TABELA PARA CADASTRAR OS LEADS';
COMMENT ON COLUMN TB_LEAD.NOME IS 'NOME DO LEAD';
COMMENT ON COLUMN TB_LEAD.EMAIL IS 'EMAIL DO LEAD';
COMMENT ON COLUMN TB_LEAD.TELEFONE IS 'TELEFONE DO LEAD';
COMMENT ON COLUMN TB_LEAD.CONSUMO IS 'CONSUMO DE ENERGIA';
COMMENT ON COLUMN TB_LEAD.CIDADE IS 'CIDADE DO LEAD';
COMMENT ON COLUMN TB_LEAD.TIPO_TELHA IS ' 0-CERÂMICA,1-ESMALTADA,2-PVC,3-CONCRETO';
COMMENT ON COLUMN TB_LEAD.ORIGEM IS '0-FACEBOOK, 1-WHATSAPP...';
COMMENT ON COLUMN TB_LEAD.ORIGEM IS '0-INATIVO, 1-ATIVO';