INSERT INTO TB_LEAD(NOME,EMAIL,TELEFONE,CONSUMO,CIDADE,TIPO_TELHA,ORIGEM,STATUS)
			VALUES ('ROBERTO DE SOUZA XAVIER JUNIOR','ROBERTO.SXAV@GMAIL.COM','65984216011',500,'NOVA BRASILANDIA',1,1,1);
			
INSERT INTO TB_LEAD(NOME,EMAIL,TELEFONE,CONSUMO,CIDADE,TIPO_TELHA,ORIGEM,STATUS)
			VALUES ('EDUARDO ROOSEVELT','DUDUZETE@GMAIL.COM','65984216012',600,'CUIABA',0,2,1);

INSERT INTO TB_LEAD(NOME,EMAIL,TELEFONE,CONSUMO,CIDADE,TIPO_TELHA,ORIGEM,STATUS)
			VALUES ('JOSE AILTON','ZEZE@GMAIL.COM','65999896025',800,'CACERES',1,1,1);

INSERT INTO TB_LEAD(NOME,EMAIL,TELEFONE,CONSUMO,CIDADE,TIPO_TELHA,ORIGEM,STATUS)
			VALUES ('LEILA PEREIRA','LEILA@GMAIL.COM','65984356509',500,'JACIARA',2,3,1);			

commit;			
												