CREATE TABLE TB_HISTORICO_LEAD (
 	ID_HIST_LEAD SERIAL CONSTRAINT PK_ID_HIST_LEAD PRIMARY KEY,
 	DESCRICAO VARCHAR(500) NOT NULL,
 	DATA DATE NOT NULL,
 	ID_LEAD BIGINT NOT NULL,
 	STATUS NUMERIC(1) DEFAULT 1,
 	FOREIGN KEY (ID_LEAD) REFERENCES TB_LEAD (ID_LEAD)
);
